#!/usr/bin/env bash
# aggregate-services.sh — merge services.json (curated) + machines/*.json (scanned)
# into REGISTRY.md with three sections: Curated & running, Unreviewed, Missing.
#
# Exit code: 0 always (advisory).

set -u

MEM_DIR="${AGENT_MEMORY_DIR:-$HOME/.local/share/agent-memory}"
SVC_DIR="$MEM_DIR/services"
CURATED="$SVC_DIR/services.json"
MACHINES_DIR="$SVC_DIR/machines"
OUT="$SVC_DIR/REGISTRY.md"
TMP="$(mktemp)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

[ -f "$CURATED" ] || echo '{}' > "$CURATED"

# Combined machines snapshot keyed by hostname
if compgen -G "$MACHINES_DIR/*.json" > /dev/null; then
  ALL_MACHINES_JSON="$(jq -s 'map({(.host): .}) | add' "$MACHINES_DIR"/*.json)"
else
  ALL_MACHINES_JSON='{}'
fi

CURATED_JSON="$(cat "$CURATED")"

{
  echo "# Tailnet Service Registry"
  echo ""
  echo "> Auto-generated by \`oh-my-opencode-pms/scripts/aggregate-services.sh\`."
  echo "> Last refresh: **$NOW** (UTC)."
  echo "> Curate by editing \`services.json\`. Scans live under \`machines/<host>.json\` — do not hand-edit."
  echo ""

  # =================================================================
  # 1. CURATED & RUNNING — intersection
  # =================================================================
  echo "## 🟢 Curated & running"
  echo ""
  jq -r --argjson all "$ALL_MACHINES_JSON" '
    [ to_entries[] as $p
      | $p.value.deployments[]? as $d
      | select(($all[$d.host].ports // []) | map(.port) | index($d.port))
      | {project:$p.key, host:$d.host, port:$d.port,
         url: (($d.url_template // "https://{host}.tail00ae77.ts.net:{port}/")
               | gsub("\\{host\\}"; $d.host) | gsub("\\{port\\}"; ($d.port|tostring))),
         repo: ($p.value.repo // "—"),
         kind: ($d.kind // "—"),
         description: ($p.value.description // "")}
    ] as $rows
    | if ($rows | length) == 0 then
        "_(nothing curated yet — see Unreviewed section below)_\n"
      else
        "| Project | Host | Port | Access URL | Repo | Kind | Notes |\n|---|---|---|---|---|---|---|\n" +
        ($rows | map("| \(.project) | \(.host) | \(.port) | [\(.url)](\(.url)) | `\(.repo)` | \(.kind) | \(.description) |") | join("\n"))
      end
  ' "$CURATED"
  echo ""
  echo ""

  # =================================================================
  # 2. UNREVIEWED — scanned ports not in curated.deployments
  # =================================================================
  echo "## 🟡 Unreviewed"
  echo ""
  echo "_Listening ports the scan found that you haven't curated. Promote by adding an entry to \`services.json\`._"
  echo ""
  jq -nr --argjson curated "$CURATED_JSON" --argjson all "$ALL_MACHINES_JSON" '
    [ $all | to_entries[] as $m
      | $m.value.ports[]? as $port
      | ([ $curated | to_entries[] | .value.deployments[]?
            | select(.host == $m.key and .port == $port.port) ] | length) as $matched
      | select($matched == 0)
      | # auto-correlate repo from cwd: walk up looking for known repo path
        ($m.value.repos // []) as $repos
      | ([ $repos[] | select((.path | rtrimstr("/")) as $rp
                              | ($port.cwd // "") | startswith($rp)) ][0] // null) as $repo
      | {host:$m.key, port:$port.port,
         process:($port.process // "—"),
         cwd:($port.cwd // "—"),
         repo_hint:(if $repo then $repo.remote else "—" end),
         collected_at:$m.value.collected_at}
    ] as $rows
    | if ($rows | length) == 0 then
        "_(no unreviewed ports — fully curated)_\n"
      else
        "| Host | Port | Process | cwd | Repo (auto) | Last scan |\n|---|---|---|---|---|---|\n" +
        ($rows | map("| \(.host) | \(.port) | \(.process) | `\(.cwd)` | `\(.repo_hint)` | \(.collected_at) |") | join("\n"))
      end
  '
  echo ""
  echo ""

  # =================================================================
  # 3. MISSING — curated deployments with no matching live port
  # =================================================================
  echo "## 🔴 Missing"
  echo ""
  echo "_Curated but not seen in latest scan. Drift alert._"
  echo ""
  jq -r --argjson all "$ALL_MACHINES_JSON" '
    [ to_entries[] as $p
      | $p.value.deployments[]? as $d
      | (if ($all[$d.host] // null) == null then "host not scanned"
         elif (($all[$d.host].ports // []) | map(.port) | index($d.port)) == null then "port not listening"
         else null end) as $why
      | select($why != null)
      | {project:$p.key, host:$d.host, port:$d.port, reason:$why,
         last_seen: (($all[$d.host].collected_at // "never"))}
    ] as $rows
    | if ($rows | length) == 0 then
        "_(nothing missing — all curated services are running)_\n"
      else
        "| Project | Host | Port | Reason | Last scan |\n|---|---|---|---|---|\n" +
        ($rows | map("| \(.project) | \(.host) | \(.port) | \(.reason) | \(.last_seen) |") | join("\n"))
      end
  ' "$CURATED"
  echo ""
  echo ""

  # =================================================================
  # 4. MACHINE STATUS
  # =================================================================
  echo "## Machine check-ins"
  echo ""
  if [ "$ALL_MACHINES_JSON" = '{}' ]; then
    echo "_(no machines have reported yet)_"
  else
    echo "| Host | Platform | Tailnet IP | FQDN | Last scan |"
    echo "|---|---|---|---|---|"
    jq -r 'to_entries[] | "| \(.key) | \(.value.platform) | \(.value.ts_ip) | \(.value.tailnet_fqdn) | \(.value.collected_at) |"' <<<"$ALL_MACHINES_JSON"
  fi
  echo ""

  echo "---"
  echo ""
  echo "_Refresh manually: \`just services-sync\` (or wait for 15-min cron)._"
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote: $OUT ($(wc -l < "$OUT") lines)"
