#!/usr/bin/env bash
# refresh-inventory.sh — regenerate <pms>/_generated/inventory.md
#
# Snapshot of this machine's agent harness, repos, tailnet, secrets, and
# memory state. Read by CLAUDE.md so any agent has up-to-date environmental
# awareness without bloating the system prompt.
#
# Run daily via cron. Also safe to run on demand.
# Exit code: 0 always (advisory).

set -u

PMS="${PMS_ROOT:-$HOME/Code/oh-my-opencode-pms}"
OUT="$PMS/_generated/inventory.md"
TMP="$(mktemp)"
mkdir -p "$(dirname "$OUT")"

# Back-compat: legacy var name still works
STACK="$PMS"

HOSTNAME_SHORT="$(hostname -s 2>/dev/null || hostname)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

{
  echo "# Machine Inventory — $HOSTNAME_SHORT"
  echo ""
  echo "> Auto-generated by \`~/Code/oh-my-opencode-pms/scripts/refresh-inventory.sh\`."
  echo "> Last refresh: **$NOW** (UTC)."
  echo "> Do NOT hand-edit — regenerated daily by cron."
  echo ""
  echo "---"
  echo ""

  # -------------------------------------------------------------------
  echo "## Harness versions"
  echo ""
  echo "| Component | Version |"
  echo "|---|---|"
  echo "| host | \`$(uname -srm 2>/dev/null)\` |"
  echo "| node | \`$(node --version 2>/dev/null || echo 'not installed')\` |"
  echo "| bun | \`$(bun --version 2>/dev/null || echo 'not installed')\` |"
  echo "| opencode | \`$(opencode --version 2>/dev/null | head -1 || echo 'not installed')\` |"
  echo "| oh-my-opencode-pms | \`$(jq -r '.version // "unknown"' ~/Code/oh-my-opencode-pms/package.json 2>/dev/null || echo 'not installed')\` |"
  echo "| pms plugin path | \`$(readlink ~/.bun/install/global/node_modules/oh-my-opencode-pms 2>/dev/null || echo 'not linked')\` |"
  echo "| gh | \`$(gh --version 2>/dev/null | head -1 || echo 'not installed')\` |"
  echo "| claude (CLI) | \`$(claude --version 2>/dev/null || echo 'not installed')\` |"
  echo "| tailscale | \`$(tailscale version 2>/dev/null | head -1 || echo 'not installed')\` |"
  echo ""

  # -------------------------------------------------------------------
  echo "## Active opencode harness"
  echo ""
  if [ -e ~/.config/opencode/opencode.jsonc ]; then
    echo "**Plugins loaded** (from \`~/.config/opencode/opencode.jsonc\`):"
    echo ""
    # Extract only the plugin array contents — JSONC-tolerant.
    # Strips line comments (`// ...`) and then pulls items between "plugin": [ ... ].
    sed 's|//.*$||' ~/.config/opencode/opencode.jsonc \
      | tr '\n' ' ' \
      | grep -oE '"plugin"[[:space:]]*:[[:space:]]*\[[^]]*\]' \
      | grep -oE '"[^"]+"' \
      | grep -v '^"plugin"$' \
      | sed 's/^/- /'
    echo ""

    echo "**MCP servers** (live, from \`opencode mcp list\`):"
    echo ""
    # Authoritative — asks opencode directly. Includes built-ins + user-added.
    if command -v opencode >/dev/null 2>&1; then
      opencode mcp list 2>/dev/null \
        | sed -E 's/\x1b\[[0-9;]*[a-zA-Z]//g' \
        | grep -E '^●' \
        | awk '{print "- "$3" ("$4")"}' \
        | sort -u
    fi
    echo ""

    if [ -e ~/.config/opencode/oh-my-opencode-pms.json ]; then
      local_preset="$(jq -r '.preset' ~/.config/opencode/oh-my-opencode-pms.json 2>/dev/null)"
      echo "**Active preset**: \`$local_preset\`"
      echo ""
      echo "**Roster** (model fallback — first available wins):"
      echo ""
      echo "| Agent | Primary model | Skills |"
      echo "|---|---|---|"
      jq -r --arg p "$local_preset" '
        .presets[$p] | to_entries[] |
        "| \(.key) | `\(.value.model[0] // "?")` | \((.value.skills // []) | join(", ")) |"
      ' ~/.config/opencode/oh-my-opencode-pms.json 2>/dev/null
      echo ""
    fi
  else
    echo "(no opencode.jsonc found)"
    echo ""
  fi

  # -------------------------------------------------------------------
  echo "## Installed skills"
  echo ""
  if [ -d ~/.config/opencode/skills ]; then
    for d in ~/.config/opencode/skills/*/; do
      name="$(basename "$d")"
      desc="$(grep -m1 '^description:' "$d/SKILL.md" 2>/dev/null | sed 's/^description: *//' | head -c 100)"
      echo "- **$name** — $desc"
    done
  fi
  echo ""

  # -------------------------------------------------------------------
  echo "## Agent overrides"
  echo ""
  if [ -d ~/.config/opencode/agent ]; then
    echo "Files in \`~/.config/opencode/agent/\` (per-subagent prompt overrides):"
    echo ""
    ls ~/.config/opencode/agent/*.md 2>/dev/null \
      | xargs -I{} basename {} \
      | sed 's/^/- /'
    echo ""
  fi

  # -------------------------------------------------------------------
  echo "## Code repos in ~/Code"
  echo ""
  echo "| Repo | Remote | Branch | Dirty? |"
  echo "|---|---|---|---|"
  for d in ~/Code/*/; do
    name="$(basename "$d")"
    # Skip non-git dirs and archives
    [ -d "$d/.git" ] || continue
    [[ "$name" == _* ]] && continue
    remote="$(git -C "$d" remote get-url origin 2>/dev/null | sed 's|https://github.com/||; s|git@github.com:||; s|\.git$||' || echo '(no origin)')"
    branch="$(git -C "$d" branch --show-current 2>/dev/null || echo '?')"
    dirty=""
    if [ -n "$(git -C "$d" status --porcelain 2>/dev/null)" ]; then
      dirty="✗"
    else
      dirty="clean"
    fi
    echo "| $name | $remote | $branch | $dirty |"
  done
  echo ""

  # -------------------------------------------------------------------
  echo "## Tailnet"
  echo ""
  if command -v tailscale >/dev/null 2>&1; then
    echo '```'
    tailscale status 2>&1 | head -20
    echo '```'
  else
    echo "(tailscale CLI not installed)"
  fi
  echo ""

  # -------------------------------------------------------------------
  echo "## Secrets vault"
  echo ""
  if [ -d ~/.config/secrets ]; then
    sec_perms="$(stat -c '%a' ~/.config/secrets 2>/dev/null || echo '?')"
    sec_count="$(ls ~/.config/secrets/*.key 2>/dev/null | wc -l | tr -d ' ')"
    echo "- vault dir: \`~/.config/secrets/\` (mode $sec_perms, $sec_count key(s))"
    echo "- loader: \`~/.config/secrets/load.sh\` (sourced from \`~/.bashrc\`)"
    if [ "$sec_count" -gt 0 ]; then
      echo "- keys present:"
      for k in ~/.config/secrets/*.key; do
        kname="$(basename "$k" .key | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
        ksize="$(wc -c < "$k" | tr -d ' ')"
        kperms="$(stat -c '%a' "$k" 2>/dev/null)"
        echo "  - \`$(basename "$k")\` → \`${kname}_API_KEY\` (${ksize}B, mode $kperms)"
      done
    fi
  else
    echo "(no ~/.config/secrets/ dir — see CLAUDE.md to set up)"
  fi
  echo ""

  # -------------------------------------------------------------------
  echo "## mem0 memory store"
  echo ""
  if [ -n "${MEM0_API_KEY:-}" ] || [ -f ~/.config/secrets/mem0.key ]; then
    # Load key if not already set
    [ -z "${MEM0_API_KEY:-}" ] && [ -f ~/.config/secrets/mem0.key ] && \
      MEM0_API_KEY="$(cat ~/.config/secrets/mem0.key)"

    # Probe: list a few recent memories to confirm reachability + count growth.
    probe=$(printf '%s\n' \
      '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"inv","version":"1.0"}}}' \
      '{"jsonrpc":"2.0","method":"notifications/initialized"}' \
      '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"search-memories","arguments":{"query":"operator harness","userId":"morton"}}}' \
      | MEM0_API_KEY="$MEM0_API_KEY" timeout 10 ~/.bun/bin/mem0-mcp 2>/dev/null \
      | grep '"id":2')

    if [ -n "$probe" ]; then
      mem_count="$(echo "$probe" | grep -oE 'Memory:' | wc -l | tr -d ' ')"
      echo "- status: **connected** (userId=\`morton\`)"
      echo "- memories returned by baseline probe: **$mem_count**"
    else
      echo "- status: **unreachable** (MEM0_API_KEY may be invalid or rate-limited)"
    fi
  else
    echo "- status: **no key** — set up via \`printf '%s' \"\$KEY\" > ~/.config/secrets/mem0.key && . ~/.config/secrets/load.sh\`"
  fi
  echo ""

  # -------------------------------------------------------------------
  echo "## Recent opencode activity"
  echo ""
  if [ -d ~/.local/share/opencode/log ]; then
    log_count="$(ls ~/.local/share/opencode/log 2>/dev/null | wc -l)"
    db_size="$(du -h ~/.local/share/opencode/opencode.db 2>/dev/null | awk '{print $1}')"
    last_log="$(ls -t ~/.local/share/opencode/oh-my-opencode-pms*.log 2>/dev/null | head -1 | xargs -I{} basename {})"
    echo "- session DB size: **$db_size**"
    echo "- log files retained: **$log_count**"
    echo "- last pms log: \`$last_log\`"
  fi
  echo ""

  # -------------------------------------------------------------------
  echo "## agent-stack tracking state"
  echo ""
  echo '```'
  git -C "$STACK" status -sb 2>&1 | head -15
  echo "---"
  echo "last 3 commits:"
  git -C "$STACK" log --oneline -3 2>&1
  echo '```'
  echo ""

  echo "---"
  echo ""
  echo "_End of inventory. Re-run: \`~/agent-stack/scripts/refresh-inventory.sh\`_"
} > "$TMP"

mv "$TMP" "$OUT"
echo "Refreshed: $OUT ($(wc -l < "$OUT") lines)"
