#!/usr/bin/env bash
# weekly-review.sh — surface drift, stale memories, and hoarder-house risk.
#
# Run weekly via cron (Sundays 06:00 local). Writes a digest to
# ~/.local/share/agent-memory/reviews/YYYY-Www.md and appends a
# `type=archive_summary` event so the orchestrator can find it.
#
# Pattern: DEV community 2026-05-18 ("What an AI agent's memory layer
# actually has to store"):
#   "Some memory stops being useful because the project has moved on...
#    A boundary gets replaced. A migration completes. A temporary
#    constraint expires. A failure mode gets designed out. If those
#    records stay mixed in with the live ones forever, the memory layer
#    slowly turns back into the same clutter problem it was supposed
#    to fix."
#
# Also pattern: agent-guard "Nightly Rollup Reports" (russellmoss, Feb 2026):
# 02:00 UTC → GitHub issue per repo summarizing average drift, peak scores.
#
# Exit code: 0 always (advisory; never breaks cron).

set -u

MEM_DIR="${AGENT_MEMORY_DIR:-$HOME/.local/share/agent-memory}"
PMS="${PMS_ROOT:-$HOME/Code/oh-my-opencode-pms}"
REVIEW_DIR="$MEM_DIR/reviews"
mkdir -p "$REVIEW_DIR"

WEEK="$(date +%Y-W%V)"
OUT="$REVIEW_DIR/$WEEK.md"
TMP="$(mktemp)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Helper: count events of a given type in events.jsonl
count_type() {
  local t="$1"
  grep -c "\"type\":\"$t\"" "$MEM_DIR/events.jsonl" 2>/dev/null || echo 0
}

# Helper: count recent events (last 7 days) of any type
count_recent() {
  python3 - <<PY 2>/dev/null
import json, datetime
cutoff = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=7))
n = 0
try:
    with open("$MEM_DIR/events.jsonl") as f:
        for line in f:
            try:
                e = json.loads(line)
                ts = datetime.datetime.fromisoformat(e["ts"].replace("Z","+00:00"))
                if ts >= cutoff: n += 1
            except Exception: pass
except FileNotFoundError: pass
print(n)
PY
}

# Helper: days since file was last modified
days_since() {
  local f="$1"
  if [ ! -f "$f" ]; then echo "n/a"; return; fi
  python3 -c "
import os, datetime
mt = os.path.getmtime('$f')
age = datetime.datetime.now() - datetime.datetime.fromtimestamp(mt)
print(f'{age.days}')
"
}

{
  echo "# Weekly Review — $WEEK"
  echo ""
  echo "> Auto-generated by \`scripts/weekly-review.sh\`."
  echo "> Generated: $NOW"
  echo ""
  echo "---"
  echo ""

  echo "## Memory store health"
  echo ""
  TOTAL=$(wc -l < "$MEM_DIR/events.jsonl" 2>/dev/null | tr -d ' ')
  RECENT=$(count_recent)
  echo "- total events: **${TOTAL:-0}**"
  echo "- new in last 7 days: **${RECENT:-0}**"
  echo "- by type:"
  for t in preference decision topology workflow fact deferred drift research_gate_violation manual archive_summary; do
    n=$(count_type "$t")
    [ "$n" -gt 0 ] && echo "  - $t: $n"
  done
  echo ""

  echo "## Research-gate violations (last 7 days)"
  echo ""
  if [ -f "$MEM_DIR/events.jsonl" ]; then
    recent_violations=$(python3 - <<PY 2>/dev/null
import json, datetime
cutoff = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=7))
matches = []
try:
    with open("$MEM_DIR/events.jsonl") as f:
        for line in f:
            try:
                e = json.loads(line)
                if e.get("type") != "research_gate_violation": continue
                ts = datetime.datetime.fromisoformat(e["ts"].replace("Z","+00:00"))
                if ts >= cutoff: matches.append(e)
            except Exception: pass
except FileNotFoundError: pass
if not matches: print("  (none — orchestrator stayed within discipline)")
else:
    for m in matches[-10:]:
        print(f"  - {m['ts']} · {m['text'][:80]}")
PY
)
    echo "$recent_violations"
  fi
  echo ""

  echo "## Decision records"
  echo ""
  if [ -d "$MEM_DIR/decisions" ]; then
    count=$(ls "$MEM_DIR/decisions" 2>/dev/null | wc -l | tr -d ' ')
    echo "- count: **$count** ADR files"
    if [ "$count" -gt 0 ]; then
      echo "- 5 most recent:"
      ls -1t "$MEM_DIR/decisions"/*.md 2>/dev/null | head -5 | while read f; do
        title=$(grep -m1 '^title:' "$f" 2>/dev/null | sed 's/^title: *//')
        echo "  - \`$(basename "$f")\` — $title"
      done
    fi
  else
    echo "(no decisions/ dir yet — use \`/remember\` or \`just remember <text>\`)"
  fi
  echo ""

  echo "## Harness doc freshness"
  echo ""
  DOC="$PMS/docs/HARNESS.md"
  AGE=$(days_since "$DOC")
  echo "- \`docs/HARNESS.md\` last modified: **$AGE days ago**"
  if [ -n "$AGE" ] && [ "$AGE" != "n/a" ] && [ "$AGE" -gt 30 ]; then
    echo "- ⚠️  >30 days since last refresh. Run \`just docs-refresh\`."
  fi
  echo ""

  echo "## Repo drift"
  echo ""
  for repo in "$PMS" "$HOME/agent-stack" "$MEM_DIR"; do
    [ -d "$repo/.git" ] || continue
    name=$(basename "$repo")
    branch=$(git -C "$repo" branch --show-current 2>/dev/null)
    dirty=$(git -C "$repo" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    ahead=$(git -C "$repo" rev-list --count "@{u}..HEAD" 2>/dev/null || echo 0)
    behind=$(git -C "$repo" rev-list --count "HEAD..@{u}" 2>/dev/null || echo 0)
    echo "- **$name** (\`$branch\`): dirty=$dirty, ahead=$ahead, behind=$behind"
  done
  echo ""

  echo "## Suggested actions"
  echo ""
  ANY=0
  if [ -n "$AGE" ] && [ "$AGE" != "n/a" ] && [ "$AGE" -gt 14 ]; then
    echo "- [ ] \`just docs-refresh\` (HARNESS.md stale)"
    ANY=1
  fi
  vio_count=$(grep -c '"type":"research_gate_violation"' "$MEM_DIR/events.jsonl" 2>/dev/null || echo 0)
  if [ "$vio_count" -gt 5 ]; then
    echo "- [ ] review research-gate violations — pattern suggests orchestrator is gaming the gate"
    ANY=1
  fi
  if [ "$ANY" = "0" ]; then
    echo "- nothing pressing — store healthy"
  fi
  echo ""

  echo "---"
  echo "_Next review: $(date -d '+7 days' +%Y-%m-%d 2>/dev/null || date +%Y-%m-%d)_"
} > "$TMP"

mv "$TMP" "$OUT"

# Also write a summary event so the orchestrator can find this in search
SUMMARY="Weekly review $WEEK: $TOTAL events total, $RECENT new this week, $vio_count research_gate_violations. Doc age $AGE days. See $OUT"
if [ -x "$HOME/.bun/bin/agent-mem" ]; then
  "$HOME/.bun/bin/agent-mem" append --type=archive_summary --tags="weekly-review,$WEEK" "$SUMMARY" 2>/dev/null || true
fi

echo "weekly-review: ok ($(wc -l < "$OUT") lines → $OUT)" >&2
exit 0
